### ISSUE TITLE
Error handling issue with custom ErrorType

### ISSUE THREAD

**Issue by MarvinNazari** [ishkawa/APIKit#104]
Hi, `Session` always return the error in `.Failure` closure as `APIError`, but i send a custom `ErrorType` and there is no way to cast the error to another, here is a example:

```Swift
public enum CustomError: ErrorType {
    case ValidationError(message: String)
}

public struct EmailSignupRequest: StarflowRequest {
    public typealias Response = STAccessToken
    public func errorFromObject(object: AnyObject, URLResponse: NSHTTPURLResponse) -> ErrorType? {
        guard let dictionary = object as? [String: AnyObject] else {
            return nil
        }
        guard let message = dictionary["error_description"] as? String else {
            return nil
        }
        return CustomError.ValidationError(message: message)
    }
}
``` 

and when i send the request like this i can print the error and it shows as `CustomError.ValidationError` but i can't handle the error!

```swift
let req = EmailSignupRequest()
Session.sendRequest(req) { result in
   switch result {
        case .Success(_):
           print("success")
        case .Failure(let error):
           print("did get error signin up  \(error)")
        }

    }
}
```
when i do like this
`let error = error as? StarflowKitError` i get `Cast from 'APIError' to unrelated type 'CustomError' always fails`

**Comment by MarvinNazari** [comment]
Sorry but i found that we could do like this

```swift
case .Failure(let error):
      switch error {
          case .UnacceptableStatusCode(_, let error as CustomError):
              switch error {
                case .ValidationError(let message):
                    self.loading.textLabel.text = message
                 }
          default:
              print(error)
          }
      }
```

**Comment by ishkawa** [comment]
In current version of APIKit, `RequestType` calls its `errorFromObject(_:URLResponse:)` if `acceptableStatusCode` doesn't contain `NSHTTPURLResponse.statusCode`. Then, it wraps the error returned by `errorFromObject(_:URLResponse:)` in `UnacceptableStatusCode`.
https://github.com/ishkawa/APIKit/blob/559efccb9be4f144bc4f2c8fb8133e5afc3a52bf/APIKit/RequestType.swift#L141-L144

Consequently, you might be able to get `CustomError` as below:

```swift
let request = EmailSignupRequest()

Session.sendRequest(request) { result in
    switch result {
    case .Success:
        print("success")
        
    case .Failure(let error):
        if case .UnacceptableStatusCode(let customError as CustomError) = error {
            // customError is CustomError
        }
    }
}
```

**Comment by MarvinNazari** [comment]
Yeah, Exactly!! thank you for answer! sorry if i ask so many questions here, i really love APIKit :)

**Comment by ishkawa** [comment]
No problem! I would love to answer your next question :smile:
