### ISSUE TITLE
Tracking upload and response callback

### ISSUE THREAD

**Issue by raulriera** [ishkawa/APIKit#120]
Hi,

I am trying to upload an image to a server, at the moment is working great.. but since I need to register a new URLSession to get the progress of the upload, this makes the APIKit skip the response callback entirely.

```swift
let session = Session(URLSession: NSURLSession(configuration: .defaultSessionConfiguration(), delegate: self, delegateQueue: nil))

session.sendRequest(request) { response in
   print("never gets called")
}
```

Am I doing this correctly? or is there another method I should be using within the library?

Thanks

**Comment by ikesyo** [comment]
Did you check [the section](https://github.com/ishkawa/APIKit/tree/1.1.4#nsurlsessiondelegate) in README?

> NOTE: `URLSessionDelegate` also implements delegate methods of `NSURLSession` to implement wrapper of `NSURLSession`, so you should call super if you override following methods.
>
- `func URLSession(_:task:didCompleteWithError:)`
- `func URLSession(_:dataTask:didReceiveData:)`
- `func URLSession(_:dataTask:didBecomeDownloadTask:)`

**Comment by raulriera** [comment]
Sorry I missed that part, although I don't know overriding any of those methods, just this one 

`func URLSession(session: NSURLSession, task: NSURLSessionTask, didSendBodyData bytesSent: Int64, totalBytesSent: Int64, totalBytesExpectedToSend: Int64)`

Although, I am a bit confused on how I am supposed to call super on this method, I will look it up. Thanks

**Comment by raulriera** [comment]
Ah, I see what I was doing wrong, I was subclassing the `NSURLSessionTaskDelegate` and not `URLSessionDelegate`

Is this a bug in the documentation? (since URLSessionDelegate is the library's one, an actual class and not the normal iOS protocol)
