### ISSUE TITLE
How to basic auth?

### ISSUE THREAD

**Issue by yuta-t** [ishkawa/APIKit#121]
Not found how to basic auth by use APIKit.

If Alamofire, can pass auth to write `.authenticate(user: user, password: password)` .

Best regards.

**Comment by ishkawa** [comment]
Unlike Alamofire, helper method for basic auth is not provided, but there are 3 ways to implement basic auth in APIKit:

1. Embed user:pass in your `baseURL` like `https://user:pass@example.com`
2. Set base64 encoded user:pass to `Authorization` HTTP header field in `configureURLRequest()`
3. Create custom `Session` and implement delegate methods in `NSURLSessionDelegate`.

1 and 2 are very easy to implement but 3 is a little bit complicated. If you use basic auth in production, I recommend 3.

**Comment by yuta-t** [comment]
Thank you for answering!
