### ISSUE TITLE
Pass an json array as request parameter

### ISSUE THREAD

**Issue by toshi0383** [ishkawa/APIKit#124]
JsonRpc has [Batch feature](http://www.jsonrpc.org/specification#batch), whose request parameter is an array of json objects, so I think `RequestType` should accept Array type as `parameters` as well as Dictionary type.
Maybe we should add `arrayParameters` to `RequestType` protocol ?

**Comment by ishkawa** [comment]
Thank you for the nice solution in #125 :sparkles:

**Comment by toshi0383** [comment]
🚀
