### ISSUE TITLE
SSL Pinning

### ISSUE THREAD

**Issue by MarvinNazari** [ishkawa/APIKit#129]
Is there anyway we could do SSL Pinning in APIKit? like [Alamofire ServerTrustPolicy](https://github.com/Alamofire/Alamofire#servertrustpolicy)

**Comment by ishkawa** [comment]
No. I'm not planning to support SSL pinning in APIKit. If you want to implement the feature in your app, customize `NSURLSessionDelegate` of `Session` (mentioned [here](https://github.com/ishkawa/APIKit#nsurlsessiondelegate)) and implement it  in `URLSession:didReceiveChallenge:completionHandler:` manually.
