### ISSUE TITLE
ld: linking against dylib not safe for use in application extensions

### ISSUE THREAD

**Issue by toshi0383** [ishkawa/APIKit#131]
`xcodebuild` complains when linking to tvOS TopShelf extension app.
I didn't know if it's okay to just enable "Allow app extension API only".

**Comment by ishkawa** [comment]
Does enabling "Allow app extension API only" solve your problem?
We're not using any of APIs marked as `NS_EXTENSION_UNAVAILABLE `, so we can set this flag `YES`.

**Comment by ishkawa** [comment]
[This issue on antitypical/Result](https://github.com/antitypical/Result/pull/26) might be related. Could you add `APPLICATION_EXTENSION_API_ONLY = YES;` to `Sources/APIKit.xcconfig` and confirm your issue is resolved?

**Comment by toshi0383** [comment]
Yep, it works for me.:smiley:  I created PR in case you needed.

**Comment by ishkawa** [comment]
Thank you for the PR :sparkles:  This issue is fixed in 1.2.1!
