### ISSUE TITLE
【Question】Example code in README failed to build

### ISSUE THREAD

**Issue by takashi** [ishkawa/APIKit#151]
Hi, I'm new to swift, so I'm sorry if I made mistake.

in XCode7.3 and swift 2.2, example code with himotoki got `'DecodedType' is not a member type of 'Self.Response'`

here's full code that i got the error. 

```swift
import Foundation

import Himotoki
import APIKit

protocol ExampleRequest : RequestType {}

extension ExampleRequest {
    var baseURL: NSURL {
        return NSURL(string: "https://example.com/")!
    }
}

extension ExampleRequest where Self.Response: Decodable, Self.Response == Self.Response.DecodedType {
    func responseFromObject(object: AnyObject, URLResponse: NSHTTPURLResponse) -> Self.Response? {
        return try? decode(object)
    }
}

```

Is there any workaround to solve this error? 

thanks.

**Comment by ishkawa** [comment]
Are you using Himotoki 2.0 or later? As the error messages indicates, `Decodable.DecodedType` is removed in the 2.0. 
https://github.com/ikesyo/Himotoki/blob/204e79dcef75595cb0a1cec4a53a82e6fdaf9e40/Sources/Decodable.swift#L9-L12

Thus, we can omit `Self.Response == Self.Response.DecodedType` in the type constraint as below:

```swift
extension ExampleRequest where Self.Response: Decodable {
    func responseFromObject(object: AnyObject, URLResponse: NSHTTPURLResponse) -> Self.Response? {
        return try? decode(object)
    }
}
```

**Comment by takashi** [comment]
@ishkawa 
yep, I'm using Himotoki, and I havent noticed `Decodable.DecodedType` has been removed... 
thank you for showing me an example. 

And can I send pull request to change README to change code? I think not a less people using Himotoki and APIKit affects this change on Himotoki.

**Comment by ishkawa** [comment]
Yes, any patches are welcome!

**Comment by takashi** [comment]
@ishkawa thx, I've sent a small pull request #152 

thanks for solving an question! you save my day.
