### ISSUE TITLE
Validate HTTP response headers

### ISSUE THREAD

**Issue by matsuda** [ishkawa/APIKit#162]
I'm sorry to be not good at English.

I want to halt a process response by validating HTTP response headers.

For example,
There is app versions in both the client app and http headers in the server response.
If it's number in the former is less than it in the latter, I want to halt a process server response i.e. parse,
and show alert to encourage users to update app.

~~~
// FooRequet
func responseFromObject(object: AnyObject, URLResponse: NSHTTPURLResponse) -> Response? {
  let headers = URLResponse. allHeaderFields
  if let version = headers["mobile-version"] where version > currentVersion { // release new version
    // halt and handling error at place calling `Session#sendRequest`
  }
  ...
  return ...
}

// ViewController
session.sendRequest(request) { result in
  // if error of app version
  presentAlert("update app")
}
~~~

Is there a solution?

Here is imagination I think casually,

~~~
// FooRequet
// add throws
func responseFromObject(object: AnyObject, URLResponse: NSHTTPURLResponse) throws -> Response? {
  // if current version is outdated
  throw FooError.AppVersionOutdated(version)
  return ...
}

// RequestType
public func parseData(data: NSData, URLResponse: NSURLResponse?) -> Result<Self.Response, APIError> {
  ...
  do {
    guard let response = responseFromObject(object, URLResponse: HTTPURLResponse) else {
        return .Failure(.InvalidResponseStructure(object))
    }
    ...
  } catch {
    return .Failure(.InvalidResponseError(error))
  }
  ...
}
~~~

Thanks.

**Comment by matsuda** [comment]
I found a solution.
I can handle by `NSURLSessionTaskDelegate`.

**Comment by ishkawa** [comment]
Thank you for the suggestion!

The solution you suggested first is exactly the same as error handling model in 2.0 (in beta). `interceptObject(_:URLResponse:)` is method to validate response. Here's an example of implmentaiton:

```swift
protocol YourServiceRequestType: RequestType {
}

extension YourServiceRequestType {
    func interceptObject(object: AnyObject, URLResponse: NSHTTPURLResponse) throws -> Response {
        guard /* Check API version in URLResponse */ else {
            throw FooError.AppVersionOutdated(version)
        }

        guard (200..<300).contains(URLResponse.statusCode) else {
            throw /* Some error */
        }

        return object
    }
}
```

See the documentation for more details.
https://github.com/ishkawa/APIKit/blob/2.0-development/Documentation/DefiningRequestProtocolForWebService.md#throwing-custom-errors-web-api-returns

**Comment by matsuda** [comment]
Thanks for your response.

Oh...,
I was going to try 2-beta, but not yet.
So, I will do it soon!
