### ISSUE TITLE
RequestError's access control

### ISSUE THREAD

**Issue by matsuda** [ishkawa/APIKit#164]
I try `2.0-development` branch just now.

`RequestError`'s access control is `internal`.
Is this on purpose?
[RequestError.swift](https://github.com/ishkawa/APIKit/blob/2.0-development/Sources/Error/RequestError.swift#L4)

Is it possible to `public`?

**Comment by ishkawa** [comment]
Good catch 🙇 This will also be fixed in #166!

**Comment by matsuda** [comment]
Thanks for quick reaction!
