### ISSUE TITLE
I want to Customize NSURLRequest

### ISSUE THREAD

**Issue by matsuda** [ishkawa/APIKit#165]
I try 2.0-dev branch.

`interceptURLRequest` is removed at this commit 022d2563db1aa039886c145d3aee41661ab81555 .
Is there how to customize NSURLRequest?

**Comment by ishkawa** [comment]
Thank you for your suggestion! I overlooked the importance of customizing NSURLRequest in #163. Actually, it is hard to customize NSURLRequest after 022d256. I've reverted #163 and restored `interceptURLRequest(_:)` in #166.

**Comment by matsuda** [comment]
Thanks for quick reaction!

I have tried, so I have no problem for now.
