### ISSUE TITLE
RequestType#configureURLRequest

### ISSUE THREAD

**Issue by minerva1129** [ishkawa/APIKit#170]
日本語ですみません。
当方swiftに関しては使い始めたばかりで見当違いな指摘かもしれませんが、RequestTypeのconfigureURLRequestの戻り値が使われていないような気がします。副作用でのconfigurationを期待するメソッドなのでしょうか？

**Comment by ishkawa** [comment]
戻り値が使われるのが正しい動作ですね。
これまで副作用だけを利用していて見落としていました！

**Comment by ishkawa** [comment]
I've fixed this issue, the return value of `configureURLRequest(_:)` is not used in `buildURLRequest()`. This will be released in upcoming version  1.4.1, and also be picked on 2.0 branch.

Thank you for the report ✨

**Comment by minerva1129** [comment]
素早い対応ありがとうございました！！🙇🏻
