### ISSUE TITLE
Updated to Version 2 but having issues with HTTP Headers

### ISSUE THREAD

**Issue by jyounus** [ishkawa/APIKit#176]
Hey there,

I thought I was using the beta for 2.0 before, but looks like I was still on 1.3!
I decided to update today and sort out all the issues. I managed to get it all refactored and building, however now I have 1 issue and that's related to the http headers.

First of all, you should include in the migration guide that ```HTTPHeaderFields``` has changed to ```headerFields```. 

Now to my problem, after I updated my existing classes to use ```headerFields```, it doesn't seem to be picking up my custom header. I'm doing something like this right now:

```
var headerFields: [String: String] {
    return [APIHeaders.BasicAuth.rawValue: constructBasicAuth()!]
}
```

Inside the ```constructBasicAuth``` function, I have some ```print()``` statements which are NOT printing in the console. I'm not sure why, but it seems like it's not using the ```headerFields``` property at all?

Do you have any ideas what I might be doing wrong? Am I maybe missing a step?

**Comment by ishkawa** [comment]
Hi jyounus,

> First of all, you should include in the migration guide that HTTPHeaderFields has changed to headerFields.

I've just updated this. Thank you for reporting!

> Now to my problem, after I updated my existing classes to use ```headerFields```, it doesn't seem to be picking up my custom header. I'm doing something like this right now:
> 
> ```
> var headerFields: [String: String] {
>     return [APIHeaders.BasicAuth.rawValue: constructBasicAuth()!]
> }
> ```
> 
> Inside the ```constructBasicAuth``` function, I have some ```print()``` statements which are NOT printing in the console. I'm not sure why, but it seems like it's not using the ```headerFields``` property at all?

I confirmed RequestType uses `headerFields` using following example request type:

```swift
struct FooRequest: RequestType {
    typealias Response = Void

    var baseURL: NSURL {
        return NSURL(string: "https://example.com")!
    }

    var method: HTTPMethod {
        return .GET
    }

    var path: String {
        return "/"
    }

    var headerFields: [String : String] {
        return ["foo": "bar"]
    }

    func responseFromObject(object: AnyObject, URLResponse: NSHTTPURLResponse) throws -> Response {
        return ()
    }
}
```

test code:

```swift
let request = FooRequest()
let URLRequest = try! request.buildURLRequest()
print(URLRequest.allHTTPHeaderFields)
// Output: Optional(["Accept": "application/json", "foo": "bar"])
```

Could you confirm that your `constructBasicAuth` function executes `print()` correctly?

**Comment by jyounus** [comment]
It turns out, I was just being stupid.... There was a problem with my NodeJS backend that was causing an issue way before my actual request on the app side way being made.

Sorry and thanks for your help! I will open a PR with some fixed typos. :)
