### ISSUE TITLE
Carthage installation failed with --use-submodules

### ISSUE THREAD

**Issue by rehsals** [ishkawa/APIKit#190]
I am trying to install APIKit with carthage
And as the result of running
`carthage update --platform iOS --use-submodules --no-use-binaries`
I get error
`
A shell task (/usr/bin/env git submodule --quiet update --init --recursive) failed with exit code 1:
fatal: reference is not a tree: 3c3be9d5f9735a034e5e9434e03f6db764e9125e
Unable to checkout '3c3be9d5f9735a034e5e9434e03f6db764e9125e' in submodule path 'Carthage/Checkouts/OHHTTPStubs'
`
I use submodules as I am building a framework and want to be able to use it outside carthage. (I am following this guide: https://robots.thoughtbot.com/creating-your-first-ios-framework)

**Comment by ishkawa** [comment]
Hi rehsals,

I've just released APIKit 2.0.5 to fix the reference to OHHTTPStubs. Please run `carthage update` again and confirm that `Carfile.resolved` looks like below:

```
github "ishkawa/APIKit" "ee42834e908c893638e3f4ed2eb7fc9c7f164145"
```

The error message says git cannot checkout to 3c3be9d5f9735a034e5e9434e03f6db764e9125e. I guess that APIKit 2.0.4 has reference to the commit but it no longer exists on the repository.

I confirmed `carthage update --platform iOS --use-submodules --no-use-binaries` with following `Cartfile` completes successfully.

```swift
github "ishkawa/APIKit"
```

```sh
$ carthage update --platform iOS --use-submodules --no-use-binaries
*** Fetching APIKit
*** Fetching Result
*** Checking out Result at "2.1.2"
*** Checking out APIKit at "2.0.5"
*** xcodebuild output can be found in /var/folders/r_/k80kcyd57511kcs0fq1t12500000gn/T/carthage-xcodebuild.3efuvu.log
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "APIKit" in APIKit.xcworkspace
```

**Comment by rehsals** [comment]
Hi ishkawa. Thank you for swift response. Indeed, with 2.0.5 it works just fine.

Offtop: watched your talk on try! Swift and can't resist trying your APIKit.

**Comment by ishkawa** [comment]
😎
