### ISSUE TITLE
Unable to send [Int] value as a parameter

### ISSUE THREAD

**Issue by yukitoto** [ishkawa/APIKit#191]
以下のようなリクエストを送っています。
idsというkeyでInt型のArrayを送信したいのですが、パラメータが`["(\n    672,\n    669\n)"]`こういった形になってしまします。
やり方が悪いのでしょうか...?
何卒よろしくお願いします。
```swift
struct deleteImage: UserImageRequestType {
            typealias Response = Bool
            
            let ids:        [Int]
            let method    = HTTPMethod.DELETE
            var path:       String { return "/v1/user_images/delete" }
            var parameters: [String: AnyObject] { return ["ids": ids] }
            
            func responseFromObject(object: AnyObject, URLResponse: NSHTTPURLResponse) -> Response? {
                 ...
        }
}
```

**Comment by yukitoto** [comment]
### UPDATE
以下のような形で一つを送ることは出来るようになりました。しかし、複数個は未だ送信出来ておりません。
```
var parameters: [String: AnyObject] {
                var params = [String: AnyObject]()
                for id in ids {
                    params["ids[]"] = id
                }
                return params
            }
```

**Comment by gin0606** [comment]
```
var parameters: [String: AnyObject] {
  return ["ids": ids.map(String.init).joinWithSeparator(",")]
}
```

とするのはどうでしょう？

**Comment by yukitoto** [comment]
出来ました！！
このようにしてparametersに含めればよいのですね。勉強不足でした。
ありがとうございます。

**Comment by gin0606** [comment]
よかったです😌

蛇足ですが、今回のような「WebAPIへのパラメタ送信方法」のような、直接ライブラリに関係ない質問は http://ja.stackoverflow.com/ などの質問系のサイトに投稿するのが望ましいです😉
（ライブラリの開発者の方針によっては、大歓迎という方もいらっしゃいます）

**Comment by yukitoto** [comment]
@gin0606 アドバイスありがとうございます！
int型のarrayに対応していない => 今後実装。ということもありうるのかな、という思いも要望も含めここでイシューを立てさせていただいたのですが、改めて考えてみると少し場違いでした。
以後そうさせていただきます！ありがとうございます。

**Comment by ishkawa** [comment]
質問と回答をありがとうございます。

DELETEメソッドではURLクエリでパラメーターを表すようになっています。URLクエリで配列を表す方法は決まっていないので、APIKitではURLクエリで配列を表す方法を提供していません。なので、gin0606さんが提案しているような、配列から1つの値へまとめてからパラメーターに渡すという方法を取るのが良いと思います。

POSTなどのHTTPボディを利用するメソッドでは、以下のプロパティで配列を扱えるようになっています。
- APIKit 1.x: `var objectParameters: AnyObject`
- APIKit 2.x: `var parameters: AnyObject?`または`var bodyParameters: BodyParametersType?`

**Comment by ishkawa** [comment]
他の言語の方が読めるように、タイトルだけ英訳させていただきました 🙇

**Comment by yukitoto** [comment]
@ishkawa 丁寧にありがとうございます...!! 大変参考になりました...!!
