### ISSUE TITLE
HTTPMethod.DELETE - prefersQueryParameters -> true

### ISSUE THREAD

**Issue by jyounus** [ishkawa/APIKit#192]
Hey there,

I've got an endpoint which I'm trying to call but it doesn't work. I've debugged the issue and it's because the .DELETE method returns true for "prefersQueryParameters". That's not what I need, I need it to return false.

I need to post an array of strings back to my endpoint via the .DELETE method, but it doesn't parse properly if it uses query parameters instead of the body parameters. 

What would be the best way for me to override the default behaviour of the .DELETE method to return false instead of true inside of "prefersQueryParameters"?

**Comment by ikesyo** [comment]
I suspect that you should implement `var bodyParameters: BodyParametersType?` instead of `var parameters: AnyObject?`. Then, query parameters will not be computed from `parameters` and the value you returned from `bodyParameters` would be used for your request type.

**Comment by jyounus** [comment]
Yeah, thats what I ended up doing and it works. Thanks. :)
