### ISSUE TITLE
Build Error at Xcode8 Swift2.3

### ISSUE THREAD

**Issue by leegun** [ishkawa/APIKit#196]
Podを使ってAPIKitを使用させて頂いております。

現在、Xcode8 Swift2.3を使用しており、
APIKitを2.0.5にアップデートを行ったのですが、
ビルドエラーになりました。
調査した結果
Support FilesのAPIKit.xcconfigに下記を追加して解決しました。

SWIFT_VERSION = 2.3

※Podの場合のみ発生するようです。

**Comment by ikesyo** [comment]
Xcode 8には最新のCocoaPods 1.1.0.rc.2が必要なのでCocoaPodsをアップデートしてください。そうすれば問題なく使用できるはずです。

https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.rc.2

```bash
$ gem update cocoapods --pre
```

---

To use Xcode 8 and CocoaPods, you should use / update to the latest CocoaPods 1.1.0.rc.2. Please update the gem.
