### ISSUE TITLE
Support dot syntax

### ISSUE THREAD

**Issue by alfredcc** [ishkawa/APIKit#222]
```swift 
Session.send(request) 
    .success { response in
        // Type of `response` is `[Repository]`,
        print(response)
    }
    .failure { error in
        self.printError(error)
    }
}
```
It can remove a lot of `switch ... case...`,I think this syntax is much more clarity.

**Comment by alfredcc** [comment]
Anyway, i like this open proj, it's amazing.

**Comment by ishkawa** [comment]
Hi @alfredcc,

Thank you for the suggestion!

`Result<T, E>` lets call-site handle both success and failure cases, because `switch` statement must have exhaustive cases. That's why I chose `Result<T, E>` and `switch` statement rather than dot syntax.
