### ISSUE TITLE
HTTP Cache

### ISSUE THREAD

**Issue by jyounus** [ishkawa/APIKit#223]
Hey there,

Does APIKit cache any requests that are made/the response that is received? If so, how? Does it use the default NSURLCache? If I modified it and did something like the following in my app delegate ```NSURLCache.setSharedURLCache(URLCache)``` would APIKit automatically pick up the changes?

Does it take e-tags into consideration?

Thanks

**Comment by ishkawa** [comment]
Hi @jyounus,

Yes. `Session.shared` uses `URLSessionConfiguration.default`, and its `urlCache` property references the same instance that `URLCache.shared` returns. You can also customize cache storage by setting the property.

```swift
var configuration = URLSessionConfiguration.default
configuration.url = /* Set your URLCache */

let adapter = URLSessionAdapter(configuration: configuration)
let session = Session(adapter: adapter)
```

**Comment by jyounus** [comment]
Ah okay. If I did what you just posted, is there any way for me to change the default Session.shared instance that's returned with my custom configured one?

**Comment by ishkawa** [comment]
`Session.shared` is provided by private static method, so we can't replace that. I recommend configuring `URLCache.shared` to customize cache behavior of `Session.shared`.

**Comment by jyounus** [comment]
Fair enough. Thanks! :)
