### ISSUE TITLE
What is the preferred testing approach when using APIKit?

### ISSUE THREAD

**Issue by ratkins** [ishkawa/APIKit#226]
I see the `Request` implementations are easily unit-testable which is nice. But what is the preferred approach to testing for clients of the `Session` API? It's declared as a class rather than a protocol so it's not simply a matter of substituting a fake a test time. I don't see a "`MockSessionAdapter`" in the test tree, but is that the appropriate hook point?

**Comment by jyounus** [comment]
Good question. 
I guess subclassing the Session class and overriding the functions isn't really ideal (or creating a completely new "MockSession" class). I would welcome a better approach to test our code with APIKit.

**Comment by ishkawa** [comment]
Hi @ratkins,

Yes, SessionAdapter is an appropriate hook point for mocking. I always create mock adapter like [this](https://github.com/tryswift/RxPagination/blob/master/Tests/TestSessionAdapter.swift). It would be great if APIKit has a flexible implementation of MockSessionAdapter for general purpose.

Of course, subclassing Session also works.

**Comment by ishkawa** [comment]
Closing this issue. Feel free to reopen this issue for the further discussion!
