### ISSUE TITLE
How to send BodyParameters

### ISSUE THREAD

**Issue by yasuralian** [ishkawa/APIKit#235]
I want to send some parameters which are JSONBodyParameters and MultipartFormDataBodyParameters at the same time.

I don't know how to post a request with parameters which are long string and image data.

Do you have any idea?

**Comment by ishkawa** [comment]
Hi @yasuralian,

I need more explanation about sending different kinds of parameters at the same time. Do you mean you would like to send JSON and multipart/form-data in the same request? Otherwise, I guess you mean you would like to express requests that has different kinds of parameters in the same request.

If you mean the latter I recommend you to define separated types. For example:

```swift
protocol YourServiceRequest {
    var baseURL: URL {
        return URL(string: "https://api.yourservice.com")!
    }
}

struct UpdateProfileRequest: YourServiceRequest {
    Response = ...

    let name: String
    let mediaID: String

    var method: HTTPRequest {
        return .post
    }

    var path: String {
        return "/update_profile"
    }

    var bodyParameters: BodyParameters? {
        return JSONBodyParameters(JSONObject: [
            "name": name,
            "mediaID": mediaID,
        ])
    }

    func response(from object: Any, urlResponse: HTTPURLResponse) throws -> Response {...}
}

struct UploadImageRequest: YourServiceRequest {
    Response = ...

    let data: Data

    var method: HTTPRequest {
        return .post
    }

    var path: String {
        return "/upload_image"
    }

    var bodyParameters: BodyParameters? {
        let part = MultipartFormDataBodyParameters.Part(
            data: data,
            name: "avatar",
            fileName: "avatar.jpg")

        return MultipartFormDataBodyParameters(parts: [part])
    }

    func response(from object: Any, urlResponse: HTTPURLResponse) throws -> Response {...}
}
```

**Comment by yasuralian** [comment]
Thank you for your suggestion, but honestly I want former one.
So I want to send JSON and multipart/form-data in the same request.
Is it able to do?

**Comment by yasuralian** [comment]
I've tried to do that, but I couldn't. 
I split up the problem request between JSON and image data, as your suggestion.   

Thank you @ishkawa

**Comment by ishkawa** [comment]
HTTP request can only have a single MIME type, so it's impossible to set MIME type both `application/json` and `multipart/form-data`.  If you want to send some text value and media in a single request, like [POST media/upload in Twitter API](https://dev.twitter.com/rest/reference/post/media/upload), you should send text values as part of multipart/form-data.

**Comment by yasuralian** [comment]
I understand it! Thank you a lot.
