### ISSUE TITLE
How to handle URLSessionTaskDelegate's functions for each `Request` object.

### ISSUE THREAD

**Issue by hyukhur** [ishkawa/APIKit#238]
Hello Ishikawa san.

I love APIKit because of it helps API implemented as a definition.
So. I'm trying to remove `Alamofire` layer.

But I meet one problem. One requirement needs hooking header field when it is redirecting to another api. But the only way I found is to make a custom url session adapter and it route calling to a `sessionTask` for every delegate functions like `handler` at `URLSessionAdapter`.

This is too complicated and seems to have a lot of duplicate code. Is there any better way?

Thanks.

**Comment by ishkawa** [comment]
Hi @hyukhur,
Thank you for loving this library 😄 

As you said, the only way to hook invocation of delegate method of URLSession is creating custom session adapter. The easiest way to create custom session adapter is subclassing URLSessionAdapter. You can override delegate methods as you need.

Here is an example that works on playground.

```swift
import PlaygroundSupport
import Foundation
import APIKit

PlaygroundPage.current.needsIndefiniteExecution = true

struct DemoRequest: Request {
    typealias Response = String

    let method = HTTPMethod.get
    let baseURL = URL(string: "https://goo.gl")!
    let path = "/Qw9e2O"

    var dataParser: DataParser {
        return StringDataParser(encoding: .utf8)
    }

    func response(from object: Any, urlResponse: HTTPURLResponse) throws -> String {
        return object as? String ?? ""
    }
}

class DemoSessionAdapter: URLSessionAdapter {
    func urlSession(_ session: URLSession, task: URLSessionTask, willPerformHTTPRedirection response: HTTPURLResponse, newRequest request: URLRequest, completionHandler: @escaping (URLRequest?) -> Void) {
        print("--> \(request)")
        completionHandler(request)
    }
}

let sessionAdapter = DemoSessionAdapter(configuration: .default)
let session = Session(adapter: sessionAdapter)

let request = DemoRequest()
session.send(request) { result in
    print(result)
}
```

The output of above code looks like:

```
--> https://example.com/
.success(...)
```

**Comment by hyukhur** [comment]
Right. Exactly same way what I did.
I'll use a subclassed session adapter for redirections and a mapping table that have which a request links with a session adapter.

Thanks.
