### ISSUE TITLE
Will you please upgrade to swift 1.2?

### ISSUE THREAD

**Issue by a11enwong** [ishkawa/APIKit#24]

**Comment by ishkawa** [comment]
Upgrading to Swift 1.2 is in progress (#22). Please use `swift-1.2` branch for now.

**Comment by a11enwong** [comment]
Thanks

**Comment by ishkawa** [comment]
Sorry to keep you waiting. [0.7.0](https://github.com/ishkawa/APIKit/releases/tag/0.7.0) is now available!
