### ISSUE TITLE
[Proposal] Add `SessionTask.originalURLRequest`

### ISSUE THREAD

**Issue by inamiy** [ishkawa/APIKit#240]
Hi @ishkawa , /cc @marty-suzuki

As discussed in #239 , retrieving a raw `URLRequest` inside `Session` will be cumbersome when using `intercept(urlRequest:)` or custom `SessionAdapter` because exclusive thread control may be necessary when `send` is called in parallel.
 
I guess the problem can be easily solved by adding `var originalRequest: URLRequest { get }` to `protocol SessionTask` so that we can refer each `URLRequest` from each `URLSessionTask`.
What do you think?

**Comment by ishkawa** [comment]
Sounds nice and reasonable. Could you work on it?

**Comment by inamiy** [comment]
Sorry to change my mind, but I'm starting to feel this proposal might not be a good one because:

- `SessionTask.originalRequest` is only used as a helper method for end-user (never used inside the library)
- There are many more `URLSessionTask` properties that can be exposed e.g. `URLSessionTask.state`, but it will make harder to mock
- `(sessionTask as? URLSessionTask)?.originalRequest` can work around in most of the cases

If you agree with above, please feel free to close the issue 🙇

**Comment by ishkawa** [comment]
OK. As you pointed out, original URLRequest is already available by type casting. Let's leave this protocol simple!
