### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by raulriera** [ishkawa/APIKit#25]
I am running into this error when trying to use the `sendRequest`, the only "thing different" that I think I am doing is embedding APIKit and LlamaKit into an umbrella framework called ProductHuntKit

```swift
let request = ProductHunt.Endpoint.Posts(day: .Today)

ProductHunt.sendRequest(request) { response in
    switch response {
    case .Success(let box):
        let content = box.unbox
        
    case .Failure(let box):
        let alertController = UIAlertController(title: "Error", message: box.unbox.localizedDescription, preferredStyle: .Alert)
        let action = UIAlertAction(title: "OK", style: .Default, handler: nil)
        alertController.addAction(action)
        self.presentViewController(alertController, animated: true, completion: nil)
    }
}
```

```
Undefined symbols for architecture x86_64:
  "__TIZFC6APIKit3API11sendRequestFMS0_US_7Request_U__FTQ_10URLSessionCSo12NSURLSession7handlerFGO8LlamaKit6ResultQQ_8ResponseCSo7NSError_T__GSqCSo20NSURLSessionDataTask_A0_", referenced from:
      __TFC11ProductHunt20DetailViewController11viewDidLoadfS0_FT_T_ in DetailViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Anything comes to mind?

**Comment by ishkawa** [comment]
You may forget to link APIKit and LlamaKit to your application target. Make sure the build target that links to ProductHuntKit also links to APIKit and LlamaKit like below.

![](http://i.gyazo.com/6de0f561bc3016f0bc731c0cdcaa7317.png)

When I remove APIKit from "Linked Frameworks and Libraries", the same error occurred.

**Comment by raulriera** [comment]
thanks for the reply, but should that happen? Both APIKit and LlamaKit are linked to the ProductHuntKit, linking them twice will defeat the purpose of the ProductKit.framework

**Comment by ishkawa** [comment]
Yes, they should be also linked to the build target even if ProductHuntKit contains them in `ProductHuntKit.framework/Frameworks/`. The error always occurs when ProductHuntKit links to other libraries, so it is not a problem of APIKit.

If you really want to keep ProductHuntKit.framework as a single framework, add source code of APIKit and LlamaKit to the build target. It is still safe way because Swift has namespace.

**Comment by raulriera** [comment]
Thank you
