### ISSUE TITLE
JSONBodyParameters - Protect adding extra escapes by JSONSerialization.data

### ISSUE THREAD

**Issue by optimusbits** [ishkawa/APIKit#263]
JSONSerialization.data scapes slashes and when used in HTTP body, this creates a whole lot of issues. We can fix it in buildEntity(). For example when we have the request with 
```
 var bodyParameters: BodyParameters? {
            
            return JSONBodyParameters(JSONObject: [
                "bodyParam1: "base64With/a"
                ])
        }
```
after call buildEntity we will get a request with body pararam: 
```
"bodyParam1: "base64With\/a"
```

**Comment by Econa77** [comment]
@optimusbits This output is the default behavior of `JSONSerialization.data(withJSONObject:,options:))`. If you don't want to escape the slash, specify the correct option in `JSONSerialization.WritingOptions` as follows:

```
var bodyParameters: BodyParameters? {
    return JSONBodyParameters(JSONObject: ["bodyParam1: "base64With/a"], writingOptions: .withoutEscapingSlashes)
}
```
