### ISSUE TITLE
There is an inconsistency in the PBXGroup references.

### ISSUE THREAD

**Issue by keisukeYamagishi** [ishkawa/APIKit#284]
There are inconsistencies in the physical paths of some directories, such as SessionAdapter and BodyParameters, and when I open them in Xcode, the text in the directories turns red.
So there are two ways to fix the path in the project.pbxproj file's  PBXGroup, or delete the path and add the name.

Which would be better?

In my opinion, modifying the path of PBXGroup is appropriate, but what do you think?　

```
7F85FB8B1C9D317300CEE132 /* SessionAdapter */ = {
			isa = PBXGroup;
			children = (
				7F7048D41D9D89F2003C99F6 /* SessionAdapter.swift */,
				7F7048D51D9D89F2003C99F6 /* URLSessionAdapter.swift */,
			);
			path = SessionAdapter;   👈 This line. 
			sourceTree = "<group>";
		};
```

**Comment by Econa77** [comment]
Fixed #287
