### ISSUE TITLE
Box framework

### ISSUE THREAD

**Issue by raulriera** [ishkawa/APIKit#35]
Does one need to include the Box framework in the main bundle? After 0.8.0 I am getting this error

```
dyld: Library not loaded: @rpath/Box.framework/Box
```

**Comment by ishkawa** [comment]
Yes, it's also necessary because it is a dependecy of Result.framework. I'll add note about about this :bow:

**Comment by ishkawa** [comment]
I forgot to close this issue :dizzy_face: In Swift 2, Box is not necessary!
