### ISSUE TITLE
Error status code

### ISSUE THREAD

**Issue by dccarmo** [ishkawa/APIKit#48]
It'd be great if API.responseErrorFromObject(object:) returned a NSHTTPURLResponse - it'd help to  validate HTTP status codes.

**Comment by dccarmo** [comment]
Or maybe return the status code.

**Comment by ishkawa** [comment]
Yes, we will add `NSHTTPURLResponse` to the arguments of `responseErrorFromObject(_:)`.

**Comment by ishkawa** [comment]
`NSHTTPURLResponse` is now available in `Request.responseFromObject(_:URLResponse:)`!
https://github.com/ishkawa/APIKit/blob/a5c6faf2c1c68f56c180354101be5fa14d971ed9/APIKit/Request.swift#L39
