### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by ikesyo** [ishkawa/APIKit#66]
To follow the [Semantic Versioning](http://semver.org/), a form `1.0.0-beta.5` would be more appropriate than `1.0.0-beta5` IMO.

**Comment by ishkawa** [comment]
OK, let's fix the format on the next version `1.0.0-beta.6`!

**Comment by ishkawa** [comment]
Released `1.0.0-beta.6`!

**Comment by ikesyo** [comment]
:+1:
