### ISSUE TITLE
Name of Request protocol

### ISSUE THREAD

**Issue by ishkawa** [ishkawa/APIKit#79]
In Swift standard library, protocol names follow naming conventions like ...able or ...Type. For example, `Equiatable`, `SequenceType` and `ErrorType`. I think `RequestType` is more suitable for the name of request protocol, and this change should be applied before 1.0.0 is released.

@ikesyo What do you think?

**Comment by ikesyo** [comment]
:+1: for `RequestType`. That is the right direction we should go in. :grin:
