### ISSUE TITLE
Mapping an array of objects

### ISSUE THREAD

**Issue by MarvinNazari** [ishkawa/APIKit#93]
Hi, There is no example on how its possible to map an array of objects, here is my issue
```/X/Client/TestRequest.swift:21:8: Type 'TestRequest' does not conform to protocol 'RequestType'``` 

the issue is that there is no `responseFromObject` function for arrays

    struct TestRequest: XPRequest {
        typealias Response = [LKObject]
    
        private var page: Int!
        private var perPage: Int!
    
        var method: HTTPMethod {
            return .GET
        }
    
       var authenticate: Bool {
           return true
       }
    
       var path: String {
           return "/api/exps"
       }
    
       init(page: Int, perPage: Int) {
           self.page = page
           self.perPage = perPage
       }
    
       var parameters: [String : AnyObject] {
           return ["page": page, "per_page": perPage]
       }
    
    }

## Update
I made a wrapper like this
    
    struct PaginatedExperience: Decodable {
        let items: [LKObject]
        static func decode(json: AnyObject) throws -> PaginatedExperience {
            return try PaginatedExperience(items: [LKObject].decode(json))
        }
    }
and it works no but its not the best way

**Comment by ikesyo** [comment]
This is not an APIKit issue and you can return `[LKObject]` because that is the typealias of `Response`. (Are you refering to Himotoki?)

**Comment by ikesyo** [comment]
Just implement it in `TestRequest`:

```swift
func responseFromObject(object: AnyObject, URLResponse: NSHTTPURLResponse) -> Response? {
    return try? decodeArray(object)
}
```

**Comment by ikesyo** [comment]
Or https://github.com/Anviking/Decodable?

**Comment by ikesyo** [comment]
This might work for Anviking/Decodable: 

```swift
func responseFromObject(object: AnyObject, URLResponse: NSHTTPURLResponse) -> Response? {
    return try? [LKObject].decode(object)
}
```

**Comment by MarvinNazari** [comment]
@ikesyo yeah, i use Anviking/Decodable, and that worked, thanks for your help
