### ISSUE TITLE
CocoaPods issue for 1.0.0-beta1x

### ISSUE THREAD

**Issue by netmaid** [ishkawa/APIKit#99]
I can not update as 1.0.0-beta13 using command `pod update`.
The CocoaPods recognize 1.0.0-beta9 as the latest version.
Maybe problem on ascending of the version string.
It will be fixed if you update version as 1.0.1.

**Comment by ishkawa** [comment]
Hi, I've just pushed `1.0.0-beta.13` podspec to CocoaPods trunk! Could you try `pod repo update && pod install` and confirm `1.0.0-beta.13` will be installed correctly?

**Comment by netmaid** [comment]
It has solved, Thanks.
Keep good work!

**Comment by ishkawa** [comment]
:wink:
